# Generated by Django 5.1.6 on 2025-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselisting',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='location',
        ),
        migrations.AddField(
            model_name='houselisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='price',
            field=models.FloatField(),
        ),
    ]
