# Generated by Django 5.1.6 on 2025-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0002_remove_houselisting_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='area',
            field=models.FloatField(blank=True, help_text='Area in sq. ft.', null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='house_age',
            field=models.IntegerField(blank=True, help_text='Age of the house in years', null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='median_income',
            field=models.FloatField(blank=True, help_text='Median income of the locality', null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='population',
            field=models.IntegerField(blank=True, help_text='Population of the area', null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
