# Generated by Django 5.1.6 on 2025-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0003_houselisting_area_houselisting_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
