# Generated by Django 5.1.6 on 2025-06-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0004_houselisting_on_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='on_sale',
            field=models.BooleanField(default=False, help_text='Mark house as currently available for sale'),
        ),
        migrations.CreateModel(
            name='ScheduleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='HousePricePrediction.houselisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
