# Generated by Django 5.1.6 on 2025-06-27 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0005_alter_houselisting_on_sale_schedulevisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houselisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'House Listing', 'verbose_name_plural': 'House Listings'},
        ),
        migrations.AlterModelOptions(
            name='schedulevisit',
            options={'ordering': ['visit_date', 'visit_time'], 'verbose_name': 'Scheduled Visit', 'verbose_name_plural': 'Scheduled Visits'},
        ),
        migrations.AddField(
            model_name='houselisting',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houselisting',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this listing prominently'),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulevisit',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulevisit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulevisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulevisit',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
