# Generated by Django 5.1.6 on 2025-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0006_alter_houselisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulevisit',
            name='notified',
            field=models.BooleanField(default=False, help_text='Has the user been notified of status change?'),
        ),
    ]
