# Generated by Django 5.1.6 on 2025-06-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousePricePrediction', '0010_alter_houselisting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('visit', 'Visit Update'), ('system', 'System Message'), ('admin', 'Admin Alert')], default='system', max_length=20),
        ),
    ]
